name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/senac-projeto-integrador/2025-1-karol-lucas-ygor-vinicius.git
          git push --mirror gitlab
